baseurl = "/"
languageCode = "en-us"
title = "Fabian Greimel"
theme = "hugo-xmin"
googleAnalytics = "UA-118026877-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

# [[menu.main]]
#     name = "Home"
#     url = "/"
#     weight = 1
[[menu.main]]
    name = "About"
    url = "/"
    weight = 20
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = 30
[[menu.main]]
    name = "Teaching"
    url = "/teaching/"
    weight = 40
[[menu.main]]
    name = "CV"
    url = "/resume/"
    weight = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [Fabian Greimel](/) 2019 | [Github](https://github.com/greimel) | [Gitlab](https://gitlab.com/greimel)"
